In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import make_classification
X,y = make_classification(n_samples = 100, n_features = 5, random_state = 1)


In [4]:
print(X)

[[-1.10325445e+00 -4.98213564e-01 -5.96224696e-02 -8.92245917e-01
  -7.01586321e-01]
 [-1.36910947e+00 -1.98837863e-01  4.90995768e-01 -5.75625745e-01
  -1.71136655e-01]
 [ 9.82517203e-01  5.85910431e-01 -1.78167075e-01  5.76990609e-01
   3.38475971e-01]
 [ 1.16188579e+00  3.03085711e+00 -1.25935066e-01  7.62080095e-01
   5.05208089e-01]
 [-6.96371397e-01  1.54335911e+00  1.09850848e+00  5.05878495e-01
   9.63827158e-01]
 [ 1.04541272e+00  1.34048197e-01 -1.22959057e+00 -3.64686886e-01
  -9.27511557e-01]
 [-3.01219255e-01 -2.54179868e-01  1.52631599e+00  1.20790857e+00
   1.71834622e+00]
 [ 1.12018826e+00 -3.44987210e-01 -1.51649333e+00 -5.77978794e-01
  -1.24017985e+00]
 [ 6.25775731e-01  6.74711526e-01 -1.29053677e+00 -7.40072673e-01
  -1.24174887e+00]
 [-1.31610584e+00  5.02740882e-01  8.96539944e-02 -9.13100629e-01
  -6.37881346e-01]
 [-1.08077536e+00  1.40754000e+00 -4.36416753e-01 -1.22975685e+00
  -1.15530746e+00]
 [-1.51555340e+00  8.84908814e-01  5.68870047e-01 -6.13337468e-01

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state=1)
print(X_train)

[[ 9.82517203e-01  5.85910431e-01 -1.78167075e-01  5.76990609e-01
   3.38475971e-01]
 [-6.53929721e-02 -6.61344243e-01  9.28661459e-01  8.24270788e-01
   1.11257376e+00]
 [-1.51594823e+00  6.23362177e-01  6.76608507e-01 -5.12259351e-01
  -2.48813316e-02]
 [ 1.50284911e+00  8.24584625e-01 -5.42169373e-01  6.28833249e-01
   1.83877931e-01]
 [ 7.18515197e-01 -1.52568032e+00 -1.39569948e+00 -7.68740194e-01
  -1.31918161e+00]
 [-1.27221465e+00 -1.44087602e+00  7.94243281e-01 -2.16847141e-01
   2.59451061e-01]
 [-7.89717763e-01 -1.86578994e-01  1.73881441e+00  1.03763331e+00
   1.70347973e+00]
 [-1.66153635e+00 -1.23312074e+00  1.13788985e+00 -1.88552557e-01
   4.63393153e-01]
 [ 1.44184425e+00 -2.30839743e-01 -1.11501987e+00  4.35701597e-02
  -5.60085539e-01]
 [-7.15728932e-01  2.01830179e-01 -9.95433704e-01 -1.47910384e+00
  -1.63971434e+00]
 [ 8.55650365e-01  1.20205486e+00 -1.19393862e+00 -4.74958573e-01
  -9.91348027e-01]
 [-1.08864222e+00  1.61694960e+00 -1.88319791e-01 -1.00227024e+00

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
print(X_train)
X_test = scaler.fit_transform(X_test)
print(X_test)

[[ 1.04527344  0.44314612 -0.17397783  0.68382349  0.32191469]
 [ 0.01072016 -0.81987876  0.86031338  0.9534102   0.99189015]
 [-1.42134599  0.48107141  0.62477902 -0.503685    0.00743185]
 [ 1.55897308  0.6848381  -0.51412481  0.74034272  0.18811132]
 [ 0.78463646 -1.69514344 -1.31171781 -0.78330235 -1.11277471]
 [-1.1807191  -1.60926689  0.73470446 -0.18162439  0.25351926]
 [-0.70437222 -0.33911061  1.617372    1.18601962  1.50331455]
 [-1.56507841 -1.39888476  1.05582974 -0.15077743  0.43002952]
 [ 1.4987458  -0.38393099 -1.04943287  0.1022845  -0.45578312]
 [-0.63132647  0.05420958 -0.93768393 -1.55774614 -1.39019324]
 [ 0.92002368  1.06708105 -1.12317959 -0.46301942 -0.82903736]
 [-0.99948652  1.48722168 -0.18346518 -1.03789856 -0.70896327]
 [-0.77817867 -0.35613868 -0.69983582 -1.41954432 -1.19070203]
 [-0.81454853 -0.8243448  -0.34990378 -1.06583331 -0.8075689 ]
 [ 0.71570078  0.47949303  0.664917    1.32892179  1.11949356]
 [-0.62297414 -0.59062877 -1.02570085 -1.64737945 -1.48

In [7]:
from sklearn.ensemble import RandomForestClassifier
classification = RandomForestClassifier(n_estimators = 100, criterion = "gini", bootstrap = "True")
classification.fit(X_train,y_train)

RandomForestClassifier(bootstrap='True')

In [8]:
classification.predict(X_test)

array([1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0])

In [9]:
print(y_test)

[1 0 0 1 1 0 0 1 0 1 1 0 0 1 1 1 0 0 0 0]
